// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceBuilder is a helper struct to build resources predefined in metadata.yaml.
// The ResourceBuilder is not thread-safe and must not to be used in multiple goroutines.
type ResourceBuilder struct {
	config ResourceAttributesConfig
	res    pcommon.Resource
}

// NewResourceBuilder creates a new ResourceBuilder. This method should be called on the start of the application.
func NewResourceBuilder(rac ResourceAttributesConfig) *ResourceBuilder {
	return &ResourceBuilder{
		config: rac,
		res:    pcommon.NewResource(),
	}
}

// SetPhpfpmPoolName sets provided value as "phpfpm.pool_name" attribute.
func (rb *ResourceBuilder) SetPhpfpmPoolName(val string) {
	if rb.config.PhpfpmPoolName.Enabled {
		rb.res.Attributes().PutStr("phpfpm.pool_name", val)
	}
}

// SetPhpfpmScrapeURI sets provided value as "phpfpm.scrape_uri" attribute.
func (rb *ResourceBuilder) SetPhpfpmScrapeURI(val string) {
	if rb.config.PhpfpmScrapeURI.Enabled {
		rb.res.Attributes().PutStr("phpfpm.scrape_uri", val)
	}
}

// Emit returns the built resource and resets the internal builder state.
func (rb *ResourceBuilder) Emit() pcommon.Resource {
	r := rb.res
	rb.res = pcommon.NewResource()
	return r
}
