// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: DefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					PhpfpmAcceptedConnections:      MetricConfig{Enabled: true},
					PhpfpmActiveProcesses:          MetricConfig{Enabled: true},
					PhpfpmIdleProcesses:            MetricConfig{Enabled: true},
					PhpfpmListenQueue:              MetricConfig{Enabled: true},
					PhpfpmListenQueueLength:        MetricConfig{Enabled: true},
					PhpfpmMaxActiveProcesses:       MetricConfig{Enabled: true},
					PhpfpmMaxChildrenReached:       MetricConfig{Enabled: true},
					PhpfpmMaxListenQueue:           MetricConfig{Enabled: true},
					PhpfpmProcessLastRequestCPU:    MetricConfig{Enabled: true},
					PhpfpmProcessLastRequestMemory: MetricConfig{Enabled: true},
					PhpfpmProcessRequestDuration:   MetricConfig{Enabled: true},
					PhpfpmProcessRequests:          MetricConfig{Enabled: true},
					PhpfpmProcessState:             MetricConfig{Enabled: true},
					PhpfpmScrapeFailures:           MetricConfig{Enabled: true},
					PhpfpmSlowRequests:             MetricConfig{Enabled: true},
					PhpfpmStartSince:               MetricConfig{Enabled: true},
					PhpfpmTotalProcesses:           MetricConfig{Enabled: true},
				},
				ResourceAttributes: ResourceAttributesConfig{
					PhpfpmPoolName:  ResourceAttributeConfig{Enabled: true},
					PhpfpmScrapeURI: ResourceAttributeConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					PhpfpmAcceptedConnections:      MetricConfig{Enabled: false},
					PhpfpmActiveProcesses:          MetricConfig{Enabled: false},
					PhpfpmIdleProcesses:            MetricConfig{Enabled: false},
					PhpfpmListenQueue:              MetricConfig{Enabled: false},
					PhpfpmListenQueueLength:        MetricConfig{Enabled: false},
					PhpfpmMaxActiveProcesses:       MetricConfig{Enabled: false},
					PhpfpmMaxChildrenReached:       MetricConfig{Enabled: false},
					PhpfpmMaxListenQueue:           MetricConfig{Enabled: false},
					PhpfpmProcessLastRequestCPU:    MetricConfig{Enabled: false},
					PhpfpmProcessLastRequestMemory: MetricConfig{Enabled: false},
					PhpfpmProcessRequestDuration:   MetricConfig{Enabled: false},
					PhpfpmProcessRequests:          MetricConfig{Enabled: false},
					PhpfpmProcessState:             MetricConfig{Enabled: false},
					PhpfpmScrapeFailures:           MetricConfig{Enabled: false},
					PhpfpmSlowRequests:             MetricConfig{Enabled: false},
					PhpfpmStartSince:               MetricConfig{Enabled: false},
					PhpfpmTotalProcesses:           MetricConfig{Enabled: false},
				},
				ResourceAttributes: ResourceAttributesConfig{
					PhpfpmPoolName:  ResourceAttributeConfig{Enabled: false},
					PhpfpmScrapeURI: ResourceAttributeConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(MetricConfig{}, ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := DefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg))
	return cfg
}

func TestResourceAttributesConfig(t *testing.T) {
	tests := []struct {
		name string
		want ResourceAttributesConfig
	}{
		{
			name: "default",
			want: DefaultResourceAttributesConfig(),
		},
		{
			name: "all_set",
			want: ResourceAttributesConfig{
				PhpfpmPoolName:  ResourceAttributeConfig{Enabled: true},
				PhpfpmScrapeURI: ResourceAttributeConfig{Enabled: true},
			},
		},
		{
			name: "none_set",
			want: ResourceAttributesConfig{
				PhpfpmPoolName:  ResourceAttributeConfig{Enabled: false},
				PhpfpmScrapeURI: ResourceAttributeConfig{Enabled: false},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadResourceAttributesConfig(t *testing.T, name string) ResourceAttributesConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	sub, err = sub.Sub("resource_attributes")
	require.NoError(t, err)
	cfg := DefaultResourceAttributesConfig()
	require.NoError(t, sub.Unmarshal(&cfg))
	return cfg
}
